# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy requirements.txt to the working directory
COPY requirements.txt .

# Upgrade pip and install dependencies
RUN pip install --upgrade pip 
RUN pip install -r requirements.txt

# Copy the current directory contents into the container at /app/
COPY . /app/

# # Expose the port on which the Django development server will run (default: 8000)
# EXPOSE 8000

# # Define the command to run your application
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
