# nginx/Dockerfile

FROM nginx:1.25

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

# # Use the official NGINX image
# FROM nginx:1.21-alpine

# # Copy nginx configuration file
# COPY nginx.conf /etc/nginx/nginx.conf

# Remove default nginx website
# RUN rm -rf /usr/share/nginx/html/*

# Copy static files from Django app
# COPY --from=django /app/static/ /usr/share/nginx/html/static/

# Expose port 80
# EXPOSE 80

# Command to run NGINX in foreground
# CMD ["nginx", "-g", "daemon off;"]
